-- Script SQL para criação da tabela alunos_presenca no Supabase

-- Criar a tabela alunos_presenca
CREATE TABLE IF NOT EXISTS public.alunos_presenca (
    codigo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_aluno UUID NOT NULL,
    data TEXT NOT NULL,
    hora_entrada TEXT NOT NULL,
    descricao TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Criar índices para melhorar performance
CREATE INDEX IF NOT EXISTS idx_alunos_presenca_codigo_aluno ON public.alunos_presenca(codigo_aluno);
CREATE INDEX IF NOT EXISTS idx_alunos_presenca_data ON public.alunos_presenca(data);

-- Criar trigger para updated_at
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_updated_at ON public.alunos_presenca;
CREATE TRIGGER set_updated_at
    BEFORE UPDATE ON public.alunos_presenca
    FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

-- Habilitar RLS (Row Level Security)
ALTER TABLE public.alunos_presenca ENABLE ROW LEVEL SECURITY;

-- Criar política RLS para permitir acesso autenticado
CREATE POLICY "Enable read access for authenticated users" ON public.alunos_presenca
    FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Enable insert access for authenticated users" ON public.alunos_presenca
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Enable update access for authenticated users" ON public.alunos_presenca
    FOR UPDATE USING (auth.role() = 'authenticated');

CREATE POLICY "Enable delete access for authenticated users" ON public.alunos_presenca
    FOR DELETE USING (auth.role() = 'authenticated');

-- Inserir alguns dados de exemplo (opcional)
-- Você precisará substituir os UUIDs pelos IDs reais dos alunos no seu sistema
INSERT INTO public.alunos_presenca (codigo_aluno, data, hora_entrada, descricao) VALUES
    ('550e8400-e29b-41d4-a716-446655440001', '2025-08-01', '08:00', 'Presente - Aula de Natação'),
    ('550e8400-e29b-41d4-a716-446655440001', '2025-08-02', '08:15', 'Presente - Aula de Natação'),
    ('550e8400-e29b-41d4-a716-446655440002', '2025-08-01', '14:00', 'Presente - Aula de Musculação'),
    ('550e8400-e29b-41d4-a716-446655440002', '2025-08-02', '14:30', 'Atrasado - Aula de Musculação')
ON CONFLICT DO NOTHING;

-- Comentários nas colunas
COMMENT ON TABLE public.alunos_presenca IS 'Tabela para registros de presença dos alunos';
COMMENT ON COLUMN public.alunos_presenca.codigo IS 'Código único da presença (chave primária)';
COMMENT ON COLUMN public.alunos_presenca.codigo_aluno IS 'UUID do aluno (referência)';
COMMENT ON COLUMN public.alunos_presenca.data IS 'Data da presença no formato texto';
COMMENT ON COLUMN public.alunos_presenca.hora_entrada IS 'Hora de entrada no formato texto';
COMMENT ON COLUMN public.alunos_presenca.descricao IS 'Descrição ou observação da presença';
